[15:02:01] (server->proxy->client)::Error:{Une connexion existante a dû être fermée par l’hôte distant}::cause.toString(){java.io.IOException: Une connexion existante a dû être fermée par l’hôte distant}
[15:02:22] (server->proxy->client)::Error:{Une connexion existante a dû être fermée par l’hôte distant}::cause.toString(){java.io.IOException: Une connexion existante a dû être fermée par l’hôte distant}
[15:22:20] (server->proxy->client)::Error:{Une connexion existante a dû être fermée par l’hôte distant}::cause.toString(){java.io.IOException: Une connexion existante a dû être fermée par l’hôte distant}
[15:22:57] (server->proxy->client)::Error:{Une connexion existante a dû être fermée par l’hôte distant}::cause.toString(){java.io.IOException: Une connexion existante a dû être fermée par l’hôte distant}
[20:54:32] (server->proxy->client)::Error:{Une connexion existante a dû être fermée par l’hôte distant}::cause.toString(){java.io.IOException: Une connexion existante a dû être fermée par l’hôte distant}
[21:04:10] (server->proxy->client)::Error:{Une connexion existante a dû être fermée par l’hôte distant}::cause.toString(){java.io.IOException: Une connexion existante a dû être fermée par l’hôte distant}
[21:06:47] (server->proxy->client)::Error:{Une connexion existante a dû être fermée par l’hôte distant}::cause.toString(){java.io.IOException: Une connexion existante a dû être fermée par l’hôte distant}
[21:10:20] (server->proxy->client)::Error:{Une connexion existante a dû être fermée par l’hôte distant}::cause.toString(){java.io.IOException: Une connexion existante a dû être fermée par l’hôte distant}
[21:11:11] (server->proxy->client)::Error:{Une connexion existante a dû être fermée par l’hôte distant}::cause.toString(){java.io.IOException: Une connexion existante a dû être fermée par l’hôte distant}
[21:15:03] (server->proxy->client)::Error:{Une connexion existante a dû être fermée par l’hôte distant}::cause.toString(){java.io.IOException: Une connexion existante a dû être fermée par l’hôte distant}
[21:16:39] (server->proxy->client)::Error:{Une connexion existante a dû être fermée par l’hôte distant}::cause.toString(){java.io.IOException: Une connexion existante a dû être fermée par l’hôte distant}
